### ISSUE TITLE
Time change from CEST to CET

### ISSUE THREAD

**Issue by HappyFr1tz** [GermanyCovid/germanycovid-discordbot#67]
### Is your feature request related to a problem? Please describe.
When you execute the commands on the Discord Bot, it always says: "Die allgemeinen Statistiken werden unsererseits täglich um 12:00 Uhr (MESZ) aktualisiert.". However, this time zone is no longer correct due to the time shift. 

### Describe your idea to us
To avoid confusion with the time zones, the addition of the time zone could generally be removed. Since the name of the project says "Germany" and therefore comes from Germany, the time zone should generally be known.

**Comment by VocalZero** [comment]
Will be implemented in v2.
