### ISSUE TITLE
Add English as language

### ISSUE THREAD

**Issue by VocalZero** [GermanyCovid/germanycovid-discordbot#7]
### Describe your idea to us
The bot should offer English as well as German. By default, English should be selected. With c!language or c!lang you can change the language to English or German.

**Comment by VocalZero** [comment]
@HappyFr1tz what do you think about it?

**Comment by HappyFr1tz** [comment]
> @HappyFr1tz what do you think about it?

I like it as an idea. However, I would find this less important than #4 .

**Comment by VocalZero** [comment]
@HappyFr1tz, @Claw76 has contacted me. He would provide the English translation.

**Comment by VocalZero** [comment]
We will not implement the idea at the moment.
