### ISSUE TITLE
No automatic updates of covid information?

### ISSUE THREAD

**Issue by f0xcb** [GermanyCovid/germanycovid-discordbot#76]
On my Discord there are no automatically sent messages about the latest covid information, but according to your website this should happen on both twitter and discord: "Auf Twitter, sowie auf Discord ist ein Programmcode dafür zuständig, die Nachrichten abzusetzen, aufgrund dessen setzt sich folgender Plan zusammen:".

**Comment by VocalZero** [comment]
This is a planned update yet to be implemented in v2 as we are still making a switch to slash commands from Discord. I will let @HappyFr1tz know that it needs to be changed on the website text.

**Comment by HappyFr1tz** [comment]
I have adapted the text passage concerned. It was not my intention that this should be misunderstood. I hope that you will continue to use our offer despite this, only until the v2 update by the commands individually query the data and/or receive the news on Twitter at the fixed times.
